// <auto-generated />
namespace Todo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TodoItem_DueDateMadeNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TodoItem_DueDateMadeNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710170721582_TodoItem_DueDateMadeNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
